### ISSUE TITLE
Major issue: not closing temporary file

### ISSUE THREAD

**Issue by ishitatsuyuki** [carlos-jenkins/python-github-webhooks#9]
I finally noticed that you missed `close()` after an uptime of one week:

```
ERROR:uwsgi_file__***:Exception on / [POST]  
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app  
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request  
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception  
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request  
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request  
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/cgi-bin/***/webhooks/github.py", line 52, in index  
    with open(join(path, 'github/config.json'), 'r') as cfg:
```

Ouch.

This was determined by this:

```
# sh -c 'readlink /proc/30756/fd/*'
/tmp/tmpjCxknv (deleted)
/tmp/tmp5p0JBV (deleted)
/tmp/tmp7W680K (deleted)
/tmp/tmpLp_FMI (deleted)
```

**Comment by ishitatsuyuki** [comment]
Wait, seems this is caused by PR #3. I will review that.

**Comment by ishitatsuyuki** [comment]
Hmm... Hello Python beginner, `mkstemp()` returns opened file descriptor. Thanks.

**Comment by ishitatsuyuki** [comment]
Tip: I have already resolved this by fdopen().
